#include <Thor/Framework/ThMathReflection.h>

namespace Thor
{

THOR_REG_ROOT_TYPE(ThVec2);
THOR_REG_ROOT_TYPE(ThVec3);
THOR_REG_ROOT_TYPE(ThVec4);
THOR_REG_ROOT_TYPE(ThVec2d);
THOR_REG_ROOT_TYPE(ThVec3d);
THOR_REG_ROOT_TYPE(ThVec4d);
THOR_REG_ROOT_TYPE(ThQuat);
THOR_REG_ROOT_TYPE(ThQuatd);

THOR_REG_ROOT_TYPE(ThMat2x2);
THOR_REG_ROOT_TYPE(ThMat3x3);
THOR_REG_ROOT_TYPE(ThMat4x4);
THOR_REG_ROOT_TYPE(ThMat2x2d);
THOR_REG_ROOT_TYPE(ThMat3x3d);
THOR_REG_ROOT_TYPE(ThMat4x4d);

}